### ISSUE TITLE
WordGuard 6.1.3 incompability?

### ISSUE THREAD

**Issue by Bodyash** [Borlea/EchoPet#76] opened 2016-06-25 17:06 UTC
[19:01:02] [Server thread/INFO]: [EchoPet][0;31;1m [WARNING] Could not create a PluginDependencyProvider for: WorldGuard! (Are you sure the type is valid?) - Only WorldGuard 6.0 and after are supported[m

i`m using WG 6.1.3 Legacy (http://builds.enginehub.org/job/worldguard?branch=master)

**Comment by Borlea** [comment] 2016-07-01 22:59
Due to no update I will be closing this as it should be working as intended in the latest build. If the issue persists please create another issue.

**Closed by Borlea** 2016-07-01 22:59 UTC
