### ISSUE TITLE
WorldGuard entry/exit deny

### ISSUE THREAD

**Issue by ridalarry** [Borlea/EchoPet#80] opened 2016-06-30 22:35 UTC
I have the plugin on my hub server and I made the spawn region has exit deny and made regions around it with entry deny, but the members can still get out of spawn by riding their pets and get out. I am using dev build 27 with worldguard 6.1.2 and worldedit 6.1.3

I even tried this on echopet config 

worldguard:
  regions:
    echopet: true
    nopet1: false
    nopet2: false
    nopet3: false
    nopet4: false
    __global__: false
    spawn: true
    allowByDefault: false
  regionEnterCheck: true

**Comment by Borlea** [comment] 2016-07-01 22:59
Due to no update I will be closing this as it should be working as intended in the latest build. If the issue persists please create another issue.

**Closed by Borlea** 2016-07-01 22:59 UTC
