### ISSUE TITLE
Human pet

### ISSUE THREAD

**Issue by random1167** [Borlea/EchoPet#90] opened 2016-07-17 19:19 UTC
![q8f051y8](https://cloud.githubusercontent.com/assets/13611085/16902593/e1ce89b8-4ca6-11e6-8022-38b97213ebce.jpg)
![e322i4j3](https://cloud.githubusercontent.com/assets/13611085/16902598/155e3102-4ca7-11e6-9f2f-b456502df488.jpg)
edit:
also i am seeing this in my console wen i am not running any commands thru the console 
`%cmd% can only be used in-game.`

**Comment by Borlea** [comment] 2016-07-19 05:17
Duplicate of #10

**Closed by Borlea** 2016-07-19 05:17 UTC
