### ISSUE TITLE
Polarbear permissions

### ISSUE THREAD

**Issue by SecretlyJealous** [Borlea/EchoPet#73] opened 2016-06-17 21:26 UTC
I give this permission
- echopet.pet.type.polarbear.*
but users can't make polarbears stand up, I'm guessing it's a similar issue to before?

**Comment by Pokemon4372** [comment] 2016-06-17 21:36
As above, had the same problem

**Comment by Borlea** [comment] 2016-06-17 23:48
Can this be testing with Build 21 http://jenkins.codingforcookies.com/job/EchoPet/21/

**Comment by Borlea** [comment] 2016-06-26 18:56
Due to no update I will be closing this as it should be working as intended after build 21. If the issue persists please create another issue.

**Closed by Borlea** 2016-06-26 18:56 UTC
