### ISSUE TITLE
Cats spazzing out.

### ISSUE THREAD

**Issue by andrewkm** [Borlea/EchoPet#93] opened 2016-07-25 07:58 UTC
https://www.ecocitycraft.com/forum/threads/bug-spastic-imaginary-kitten.153663/

Not sure if this is something that EchoPet can fix on it's end however. Just making an issue for it in case it is.

**Comment by Borlea** [comment] 2016-07-26 00:59
Duplicate of #84

**Closed by Borlea** 2016-07-26 00:59 UTC

**Comment by andrewkm** [comment] 2016-07-26 01:14
Oh my bad literally forgot I made a ticket on this before. Sorry @borlea
