### ISSUE TITLE
1.9.4 Support

### ISSUE THREAD

**Issue by mibby** [Borlea/EchoPet#60] opened 2016-05-10 22:13 UTC
Spigot 1.9.4 has been released for MC 1.9.4.

```
[15:03:37] [Server thread/INFO]: [EchoPet] Enabling EchoPet v1.0.1-b6
[15:03:37] [Server thread/INFO]: [EchoPet] [INFO] EchoPet v1.0.1-b6 is not compatible with this version of Spigot
[15:03:37] [Server thread/INFO]: [EchoPet] [INFO] Initialisation failed. Please update the plugin.
```

**Comment by Borlea** [comment] 2016-05-11 20:14
I'm unable to access my computer at this time. Maybe someone else can do a PR?

**Comment by Nickshelton80** [comment] 2016-05-11 23:48
@Borlea Is it as simple as changing v1_9_R1 to v1_9_R2? If so I can attempt that lol

**Comment by mibby** [comment] 2016-05-12 02:16
@Nickshelton80 No. Some NMS needs to be adjusted.

**Comment by mibby** [comment] 2016-05-12 03:57
@Borlea Take a look at this fork.
https://github.com/FrostMiser/EchoPet

**Comment by Borlea** [comment] 2016-05-12 04:18
@frostmiser
Looks like our best hope atm, slight issue is he removed 1.9.0-3 support which is not ideal

**Comment by mibby** [comment] 2016-05-12 05:11
@frostmiser Also need to change the pom to compile against spigot/craftbukkit 1.9.4-R0.1-SNAPSHOT in these locations. Else it won't compile.

https://github.com/FrostMiser/EchoPet/blob/master/pom.xml#L46
https://github.com/FrostMiser/EchoPet/blob/master/modules/v1_9_R2/pom.xml#L43
https://github.com/FrostMiser/EchoPet/blob/master/modules/v1_9_R2/pom.xml#L60
https://github.com/FrostMiser/EchoPet/blob/master/modules/EchoPet/pom.xml#L43

**Comment by Borlea** [comment] 2016-05-12 18:11
controls being inverted is incorrect variables. I'll see if I can contact a friend to update it. Might need to hope in others nms knowledge till I can do it myself

**Comment by mibby** [comment] 2016-05-13 05:13
@Borlea @frostmiser's newer commits seem to fix some of the problems, but there are still issues with the fork. Such as you can't put a pet on your head. It despawns a second later. Then if you type the hat command two more times in a row, this error occurs.

```
[22:09:34] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pet hat' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[patched_1.9.4.jar:git-Paper-737]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:664) ~[patched_1.9.4.jar:git-Paper-737]
	at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1387) [patched_1.9.4.jar:git-Paper-737]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1192) [patched_1.9.4.jar:git-Paper-737]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.4.jar:git-Paper-737]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.4.jar:git-Paper-737]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-737]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-737]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:818) [patched_1.9.4.jar:git-Paper-737]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-737]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:728) [patched_1.9.4.jar:git-Paper-737]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:627) [patched_1.9.4.jar:git-Paper-737]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
	at com.dsh105.echopet.api.pet.Pet.setAsHat(Pet.java:359) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:247) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.9.4.jar:git-Paper-737]
	... 14 more
```

Riding also seems to be janky (i.e. laggy, stuttering), and riding an enderdragon, your rotation is all screwed up. The enderdragon also doesn't move continuously like before.

**Comment by Borlea** [comment] 2016-05-13 22:52
I'm able to use my computer, I'll attempt to do an update asap and write down a few notes for a few more nms related variables/methods for easier updating in the future.

**Comment by mibby** [comment] 2016-05-14 02:41
I'll be here to test as soon as you push stuff to the repo. :)

**Comment by Borlea** [comment] 2016-05-14 05:29
@mibby http://jenkins.codingforcookies.com/job/EchoPet/9/ If you haven't already seen

**Comment by mibby** [comment] 2016-05-14 18:58
@Borlea 

Trying to wear a pet with a hat ```/pet hat```
```
[15:05:23] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'pet hat' in com.dsh105.echopet.commands.util.DynamicPluginCommand(pet)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[patched_1.9.4.jar:git-Paper-740]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:664) ~[patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1387) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1192) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-740]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:818) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:728) [patched_1.9.4.jar:git-Paper-740]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:627) [patched_1.9.4.jar:git-Paper-740]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
	at com.dsh105.echopet.api.pet.Pet.setAsHat(Pet.java:359) ~[?:?]
	at com.dsh105.echopet.commands.PetCommand.onCommand(PetCommand.java:247) ~[?:?]
	at com.dsh105.echopet.commands.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:46) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.9.4.jar:git-Paper-740]
	... 14 more
```

**Comment by mibby** [comment] 2016-05-14 19:00
Trying to stack a pet, riding another pet. ```/pet squid squid```

```
[15:07:30] [Server thread/WARN]: Entity threw exception at world:-6255.300000011921,73.0,4034.300000011921
[15:07:30] [Server thread/WARN]: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_9_R2.entity.CraftCreature cannot be cast to org.bukkit.entity.Player
[15:07:30] [Server thread/WARN]: 	at com.dsh105.echopet.compat.nms.v1_9_R2.entity.EntityPet.g(EntityPet.java:408)
[15:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.EntityLiving.n(EntityLiving.java:1969)
[15:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.EntityInsentient.n(EntityInsentient.java:490)
[15:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.EntityLiving.m(EntityLiving.java:1804)
[15:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.EntityInsentient.m(EntityInsentient.java:250)
[15:07:30] [Server thread/WARN]: 	at com.dsh105.echopet.compat.nms.v1_9_R2.entity.EntityPet.m(EntityPet.java:503)
[15:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.World.entityJoinedWorld(World.java:1727)
[15:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.World.g(World.java:1702)
[15:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.World.tickEntities(World.java:1527)
[15:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.WorldServer.tickEntities(WorldServer.java:638)
[15:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:890)
[15:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403)
[15:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:728)
[15:07:30] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:627)
[15:07:30] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Borlea** [comment] 2016-05-14 19:29
The pet riding a pet thing should be fixed in build 10, I'm unable to reproduce the hat one though.

**Comment by mibby** [comment] 2016-05-14 19:31
It seems to occur when you type ```/pet hat``` three times in a row. One to put the pet on your head, one to remove it, one to put it on again.

**Comment by Borlea** [comment] 2016-05-14 19:32
Ahh yup.. Interesting

**Comment by Borlea** [comment] 2016-05-14 23:54
@mibby Forced build 11. Should fix it, keep the bugs coming.. Hopefully tomorrow I can release an update on spigot

**Comment by Borlea** [comment] 2016-05-16 21:40
Due to no other reports of bugs I'll be closing this.

**Closed by Borlea** 2016-05-16 21:40 UTC

**Comment by mibby** [comment] 2016-05-21 20:18
@Borlea Apologies, been caught up with work. I'll create new tickets for issues I find. :)
