### ISSUE TITLE
EchoPet Not Storing Data in MySQL

### ISSUE THREAD

**Issue by Arctomium** [Borlea/EchoPet#72] opened 2016-06-15 06:32 UTC
I've setup MySQL on my server and added the MySQL connection options into the config.yml but when players get their pets it works perfectly but after restarting the server none of the players have their pets, I've check the Database with phpMyAdmin and in the direct console and there are no tables or anything the database is completely empty.

EchoPet isn't creating any tables or anything in the MySQL Database.

**Comment by Borlea** [comment] 2016-06-16 00:21
Works perfectly for me.

**Comment by Borlea** [comment] 2016-07-01 22:59
Due to no update I will be closing this as it should be working as intended in the latest build. If the issue persists please create another issue.

**Closed by Borlea** 2016-07-01 22:59 UTC
